In [1]:
import pandas as pd
import os

## Hyperparameter tunning analysis

In [2]:
# def analyze_hyperparameters(file_path):
#     # Load the CSV file
#     data = pd.read_csv(file_path)

#     # Group by the hyperparameters and calculate the mean success rate and average relative error
#     hyperparameter_performance = data.groupby(['flips', 'cooling_rate', 'max_iter']).agg(
#         avg_success_rate=pd.NamedAgg(column='success', aggfunc='mean'),
#         avg_rel_error=pd.NamedAgg(column='rel_error', aggfunc='mean')
#     ).reset_index()

#     # Sort by success rate and relative error to find the best parameters
#     best_hyperparameters = hyperparameter_performance.sort_values(by=['avg_success_rate', 'avg_rel_error'], ascending=[False, True])

#     # return best_hyperparameters

In [3]:
# file_path = 'SA_RESULTS/hyperparameter_tunning/hyperparameter_tunning_results.csv'
# data = pd.read_csv(file_path)

# data.head()

In [4]:
# # Example usage:
# best_params = analyze_hyperparameters(file_path)
# best_params.head()

In [5]:
# file_path = 'SA_RESULTS/hyperparameter_tunning/large_hyperparameter_tunning_results.csv'
# data = pd.read_csv(file_path)

# data.head()

In [6]:
# # Example usage:
# best_params = analyze_hyperparameters(file_path)
# best_params.head()


## Analysis of tighter hyperparameter tunning

In [7]:
# def analyze_tighter_hyperparameters(file_path):
#     # Load the CSV file
#     data = pd.read_csv(file_path)

#     # Group by the hyperparameters and calculate the mean success rate and average relative error
#     hyperparameter_performance = data.groupby(['initial_flips_ratio', 'cooling_rate', 'conf_type', 'heating_on']).agg(
#         avg_success_rate=pd.NamedAgg(column='success_rate', aggfunc='mean'),
#         avg_rel_error=pd.NamedAgg(column='avg_rel_error', aggfunc='mean'),
#         avg_runtime=pd.NamedAgg(column='avg_runtime', aggfunc='mean')
#     ).reset_index()

#     # Sort by success rate and relative error to find the best parameters
#     best_hyperparameters = hyperparameter_performance.sort_values(by=['avg_success_rate', 'avg_rel_error', 'avg_runtime'], ascending=[False, True, True])

#     return best_hyperparameters

In [8]:
# df_1_file_path = 'SA_RESULTS/beta_testing/tighter_tunning_beta_test.csv'
# df_1 = pd.read_csv(df_1_file_path)
# df_1.head(10)

In [9]:
# best_params = analyze_tighter_hyperparameters(df_1_file_path)
# best_params.head()

## Comprehensive table generation beta testing

In [10]:
# df = pd.read_csv('SA_RESULTS/beta_testing/comprehensive_table_results.csv')
# df

### Small Data Comprehensive Table

In [11]:
df_small = pd.read_csv('SA_RESULTS/small_comprehensive_table/small_data_results.csv')
df_small

,name,input_size,initial_flips,cooling_rate,max_iter,success_rate,avg_rel_error,avg_runtime,avg_best_value,real_value
0,small_1,10,5,0.995,80000,1.0,0.0,6.92,295.00,295.0000
1,small_2,20,5,0.995,80000,0.7,0.0,7.03,1020.50,1024.0000
2,small_3,4,5,0.995,80000,1.0,0.0,6.88,35.00,35.0000
3,small_4,4,5,0.995,80000,1.0,0.0,6.86,23.00,23.0000
4,small_5,15,5,0.995,80000,1.0,0.0,6.95,481.07,481.0694
5,small_6,10,5,0.995,80000,1.0,0.0,7.06,52.00,52.0000
6,small_7,7,5,0.995,80000,1.0,0.0,6.94,107.00,107.0000
7,small_8,23,5,0.995,80000,0.0,0.0,6.94,9743.70,9767.0000
8,small_9,5,5,0.995,80000,1.0,0.0,7.02,130.00,130.0000
9,small_10,20,5,0.995,80000,0.8,0.0,6.98,1023.30,1025.0000

### Large Data Comprehensive Table

In [12]:
df_large = pd.read_csv('SA_RESULTS/large_comprehensive_table/large_data_results.csv')
df_large

,name,input_size,initial_flips,cooling_rate,max_iter,success_rate,avg_rel_error,avg_runtime,avg_best_value,real_value
0,large_1,100,3,0.995,80000,0.1,0.04,7.16,8811.7,9147.0
1,large_2,200,3,0.995,80000,0.0,0.03,7.14,10896.4,11238.0
2,large_3,500,3,0.995,80000,0.0,0.03,7.23,28080.2,28857.0
3,large_4,1000,3,0.995,80000,0.0,0.01,8.08,53812.5,54503.0
4,large_5,2000,3,0.995,80000,0.0,0.01,9.08,109763.4,110625.0
5,large_6,5000,3,0.995,80000,0.0,0.00,11.13,275776.2,276457.0
6,large_7,10000,3,0.995,80000,0.0,0.00,13.34,563056.0,563647.0
7,large_8,100,3,0.995,80000,0.0,0.07,7.74,1403.4,1514.0
8,large_9,200,3,0.995,80000,0.0,0.07,7.56,1527.4,1634.0
9,large_10,500,3,0.995,80000,0.0,0.03,8.01,4439.6,4566.0
10,large_11,1000,3,0.995,80000,0.0,0.01,8.62,8924.5,9052.0
11,large_12,2000,3,0.995,80000,0.0,0.01,9.77,17863.2,18051.0
12,large_13,5000,3,0.995,80000,0.0,0.00,11.35,44199.3,44356.0
13,large_14,10000,3,0.995,80000,0.0,0.00,13.55,90071.5,90204.0
14,large_15,100,3,0.995,80000,0.0,0.05,7.36,2285.0,2397.0
15,large_16,200,3,0.995,80000,0.0,0.04,7.59,2580.9,2697.0
16,large_17,500,3,0.995,80000,0.0,0.02,7.92,6984.7,7117.0
17,large_18,1000,3,0.995,80000,0.0,0.01,8.23,14227.7,14390.0
18,large_19,2000,3,0.995,80000,0.0,0.01,8.67,28760.6,28919.0
19,large_20,5000,3,0.995,80000,0.0,0.00,10.39,72362.0,72505.0
20,large_21,10000,3,0.995,80000,0.0,0.00,13.15,146748.8,146919.0

### Concat tables to get all data

In [17]:
df_concat = pd.concat([df_small, df_large])
print(df_concat)

        name  input_size  initial_flips  cooling_rate  max_iter  success_rate  \
0    small_1          10              5         0.995     80000           1.0
1    small_2          20              5         0.995     80000           0.7
2    small_3           4              5         0.995     80000           1.0
3    small_4           4              5         0.995     80000           1.0
4    small_5          15              5         0.995     80000           1.0
5    small_6          10              5         0.995     80000           1.0
6    small_7           7              5         0.995     80000           1.0
7    small_8          23              5         0.995     80000           0.0
8    small_9           5              5         0.995     80000           1.0
9   small_10          20              5         0.995     80000           0.8
0    large_1         100              3         0.995     80000           0.1
1    large_2         200              3         0.995     80000           0.0
2    large_3         500              3         0.995     80000           0.0
3    large_4        1000              3         0.995     80000           0.0
4    large_5        2000              3         0.995     80000           0.0
5    large_6        5000              3         0.995     80000           0.0
6    large_7       10000              3         0.995     80000           0.0
7    large_8         100              3         0.995     80000           0.0
8    large_9         200              3         0.995     80000           0.0
9   large_10         500              3         0.995     80000           0.0
10  large_11        1000              3         0.995     80000           0.0
11  large_12        2000              3         0.995     80000           0.0
12  large_13        5000              3         0.995     80000           0.0
13  large_14       10000              3         0.995     80000           0.0
14  large_15         100              3         0.995     80000           0.0
15  large_16         200              3         0.995     80000           0.0
16  large_17         500              3         0.995     80000           0.0
17  large_18        1000              3         0.995     80000           0.0
18  large_19        2000              3         0.995     80000           0.0
19  large_20        5000              3         0.995     80000           0.0
20  large_21       10000              3         0.995     80000           0.0

    avg_rel_error  avg_runtime  avg_best_value   real_value
0            0.00         6.92          295.00     295.0000
1            0.00         7.03         1020.50    1024.0000
2            0.00         6.88           35.00      35.0000
3            0.00         6.86           23.00      23.0000
4            0.00         6.95          481.07     481.0694
5            0.00         7.06           52.00      52.0000
6            0.00         6.94          107.00     107.0000
7            0.00         6.94         9743.70    9767.0000
8            0.00         7.02          130.00     130.0000
9            0.00         6.98         1023.30    1025.0000
0            0.04         7.16         8811.70    9147.0000
1            0.03         7.14        10896.40   11238.0000
2            0.03         7.23        28080.20   28857.0000
3            0.01         8.08        53812.50   54503.0000
4            0.01         9.08       109763.40  110625.0000
5            0.00        11.13       275776.20  276457.0000
6            0.00        13.34       563056.00  563647.0000
7            0.07         7.74         1403.40    1514.0000
8            0.07         7.56         1527.40    1634.0000
9            0.03         8.01         4439.60    4566.0000
10           0.01         8.62         8924.50    9052.0000
11           0.01         9.77        17863.20   18051.0000
12           0.00        11.35        44199.30   44356.0000
13           0.00        13.55        90071.50   90204.0000
14           0.05         7.36         2285.00    2397.0000
15           0.04         7.59         2580.90    2697.0000
16           0.02         7.92         6984.70    7117.0000
17           0.01         8.23        14227.70   14390.0000
18           0.01         8.67        28760.60   28919.0000
19           0.00        10.39        72362.00   72505.0000
20           0.00        13.15       146748.80  146919.0000

In [14]:
comprehensive_table_sa = df_concat[['name','input_size', 'avg_runtime', 'avg_best_value', 'avg_rel_error']]
print(comprehensive_table_sa)

        name  input_size  avg_runtime  avg_best_value  avg_rel_error
0    small_1          10         6.92          295.00           0.00
1    small_2          20         7.03         1020.50           0.00
2    small_3           4         6.88           35.00           0.00
3    small_4           4         6.86           23.00           0.00
4    small_5          15         6.95          481.07           0.00
5    small_6          10         7.06           52.00           0.00
6    small_7           7         6.94          107.00           0.00
7    small_8          23         6.94         9743.70           0.00
8    small_9           5         7.02          130.00           0.00
9   small_10          20         6.98         1023.30           0.00
0    large_1         100         7.16         8811.70           0.04
1    large_2         200         7.14        10896.40           0.03
2    large_3         500         7.23        28080.20           0.03
3    large_4        1000         8.08        53812.50           0.01
4    large_5        2000         9.08       109763.40           0.01
5    large_6        5000        11.13       275776.20           0.00
6    large_7       10000        13.34       563056.00           0.00
7    large_8         100         7.74         1403.40           0.07
8    large_9         200         7.56         1527.40           0.07
9   large_10         500         8.01         4439.60           0.03
10  large_11        1000         8.62         8924.50           0.01
11  large_12        2000         9.77        17863.20           0.01
12  large_13        5000        11.35        44199.30           0.00
13  large_14       10000        13.55        90071.50           0.00
14  large_15         100         7.36         2285.00           0.05
15  large_16         200         7.59         2580.90           0.04
16  large_17         500         7.92         6984.70           0.02
17  large_18        1000         8.23        14227.70           0.01
18  large_19        2000         8.67        28760.60           0.01
19  large_20        5000        10.39        72362.00           0.00
20  large_21       10000        13.15       146748.80           0.00

In [16]:
print(comprehensive_table_sa[['name', 'input_size']])

        name  input_size
0    small_1          10
1    small_2          20
2    small_3           4
3    small_4           4
4    small_5          15
5    small_6          10
6    small_7           7
7    small_8          23
8    small_9           5
9   small_10          20
0    large_1         100
1    large_2         200
2    large_3         500
3    large_4        1000
4    large_5        2000
5    large_6        5000
6    large_7       10000
7    large_8         100
8    large_9         200
9   large_10         500
10  large_11        1000
11  large_12        2000
12  large_13        5000
13  large_14       10000
14  large_15         100
15  large_16         200
16  large_17         500
17  large_18        1000
18  large_19        2000
19  large_20        5000
20  large_21       10000